"""Generate the frozen / low-shot / pretrained-vs-scratch benchmark matrix.

The decisive experiment for the "recipe dominates representation" story: hold
the decoder + recipe FIXED and vary only

    encoder state : {frozen, finetune}
    init          : {pretrained, scratch}
    data fraction : {1, 5, 10, 25, 100}%
    backbone      : the 11 CT foundation encoders

Each emitted config reuses the backbone's own ``model:`` block from
``configs/models/<backbone>.yaml`` (so the ViT probe-honest ``pyramid_mode:
upsample`` necks carry through unchanged) and adds only the four experimental
knobs. Recipe (train:) stays locked in base.yaml; head/eval untouched. Batch is
made UNIFORM across the whole matrix (bs=2, accum=2 -> optimizer batch 8) so
frozen-vs-finetune and pretrained-vs-scratch carry no batch-size confound — the
existing headline sweep (each model at its own batch) stays a SEPARATE table.

Usage:
    python -m scripts.gen_lowshot_configs               # write all configs + MANIFEST.csv
    python -m scripts.gen_lowshot_configs --dry-run     # just print the plan

Outputs: configs/lowshot/<run_name>.yaml  +  configs/lowshot/MANIFEST.csv
"""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
MODELS_DIR = REPO / "configs" / "models"
OUT_DIR = REPO / "configs" / "lowshot"

# The 11 encoders from the headline sweep (config stem -> short tag for names).
BACKBONES = {
    "ctfm": "ctfm",
    "vista3d": "vista3d",
    "biomedparse": "biomedparse",
    "suprem_unet": "supUnet",
    "suprem_segresnet": "supSegres",
    "suprem_swinunetr": "supSwin",
    "voco_b": "vocoB",
    "voco_h": "vocoH",
    "ctclip": "ctclip",
    "sam_med3d": "samMed3d",
    "dino3d": "dino3d",
}

FRACTIONS = [0.01, 0.05, 0.10, 0.25, 1.00]
# (freeze_backbone, pretrained, tag)
CONDITIONS = [
    (True, True, "frz_pt"),    # frozen probe of the pretrained representation (headline)
    (True, False, "frz_sc"),   # frozen random-feature floor (control)
    (False, True, "ft_pt"),    # full finetune from pretrained
    (False, False, "ft_sc"),   # full finetune from scratch (the convergence control)
]

# Uniform batch across the matrix to remove the batch-size confound.
UNIFORM_BATCH_SIZE = 2
UNIFORM_GRAD_ACCUM = 2


def _frac_tag(f: float) -> str:
    return f"f{int(round(f * 100)):03d}"


def _load_model_block(stem: str) -> dict:
    cfg = yaml.safe_load((MODELS_DIR / f"{stem}.yaml").read_text())
    if "model" not in cfg:
        raise SystemExit(f"{stem}.yaml has no model: block")
    return cfg["model"]


def build(dry_run: bool = False) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    for stem, tag in BACKBONES.items():
        base_model = _load_model_block(stem)
        for freeze, pretrained, cond in CONDITIONS:
            for frac in FRACTIONS:
                run = f"ls_{tag}_{cond}_{_frac_tag(frac)}"
                model = dict(base_model)
                model["batch_size"] = UNIFORM_BATCH_SIZE
                model["grad_accum_steps"] = UNIFORM_GRAD_ACCUM
                model["freeze_backbone"] = freeze
                model["pretrained"] = pretrained
                doc = {"model": model, "data": {"train_fraction": float(frac)}}
                rows.append({
                    "run_name": run,
                    "config": f"configs/lowshot/{run}.yaml",
                    "backbone": stem,
                    "freeze_backbone": freeze,
                    "pretrained": pretrained,
                    "train_fraction": frac,
                    "condition": cond,
                })
                if not dry_run:
                    header = ("# AUTO-GENERATED by scripts/gen_lowshot_configs.py — "
                              "do not edit by hand.\n")
                    (OUT_DIR / f"{run}.yaml").write_text(
                        header + yaml.safe_dump(doc, sort_keys=False))

    if not dry_run:
        with (OUT_DIR / "MANIFEST.csv").open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)

    n = len(rows)
    print(f"{'PLANNED' if dry_run else 'WROTE'} {n} configs "
          f"({len(BACKBONES)} backbones x {len(CONDITIONS)} conditions x "
          f"{len(FRACTIONS)} fractions)")
    print(f"  conditions : {[c for *_, c in CONDITIONS]}")
    print(f"  fractions  : {[f'{int(f*100)}%' for f in FRACTIONS]}")
    if not dry_run:
        print(f"  -> {OUT_DIR}  (+ MANIFEST.csv)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    build(dry_run=args.dry_run)
