#!/usr/bin/env bash
# Manifest-driven, resume-resilient launcher for the frozen/low-shot/scratch
# matrix (configs/lowshot/, generated by scripts.gen_lowshot_configs). Runs the
# selected configs SEQUENTIALLY on ONE GPU, each with the same OOM-resume loop as
# the single-run launchers (see [[training-node-shared-oom]]). Use two instances
# with disjoint filters to fill both GPUs.
#
# Filters (regex, matched against MANIFEST.csv columns; default = everything):
#   COND=frz_pt|frz_sc     condition column
#   FRAC=1.0               train_fraction column (e.g. 1.0, 0.25, 0.01)
#   BACKBONE=ctfm|vista3d  backbone column
#   GPU=0                  physical GPU (default 0)
#
# Examples:
#   # Stage 0 (headline): frozen pretrained + frozen-scratch floor @ 100%, all 11
#   GPU=0 COND='frz_pt|frz_sc' FRAC=1.0 setsid nohup bash scripts/run_lowshot_matrix.sh >/dev/null 2>&1 &
#   # Split across GPUs by backbone:
#   GPU=1 COND='frz_pt|frz_sc' FRAC=1.0 BACKBONE='vista3d|voco|sam|dino|ctclip' bash scripts/run_lowshot_matrix.sh
#
# Per-fraction epoch caps (fixed-epoch low-shot protocol + early stop). Override
# any with env, e.g. EP_100=500. Tiny fractions overfit fast; capping saves time
# without changing the early-stop-selected checkpoint.
: "${EP_001:=200}"; : "${EP_005:=300}"; : "${EP_010:=400}"; : "${EP_025:=500}"; : "${EP_100:=500}"

REPO="/store/home/skrljl/projects/foundation_models/unified"
PY="/store/home/skrljl/projects/foundation_models/env/bin/python"
cd "$REPO" || { echo "cannot cd to $REPO"; exit 1; }

export CUDA_VISIBLE_DEVICES="${GPU:-0}"
export WANDB_MODE="${WANDB_MODE:-online}"
export TOKENIZERS_PARALLELISM=false
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

MANIFEST="$REPO/configs/lowshot/MANIFEST.csv"
[ -f "$MANIFEST" ] || { echo "no MANIFEST.csv — run: python -m scripts.gen_lowshot_configs"; exit 1; }
COND="${COND:-.}"; FRAC="${FRAC:-.}"; BACKBONE="${BACKBONE:-.}"
MAX_TRIES="${MAX_TRIES:-20}"; FAST_CRASH_SECS="${FAST_CRASH_SECS:-180}"; FAST_CRASH_CAP="${FAST_CRASH_CAP:-3}"

MATRIX_DIR="$REPO/runs/lowshot"; mkdir -p "$MATRIX_DIR"
QLOG="$MATRIX_DIR/queue_gpu${CUDA_VISIBLE_DEVICES}.log"
qlog() { echo "[$(date +%F\ %T)] $*" | tee -a "$QLOG"; }

epochs_for() { case "$1" in 0.01) echo "$EP_001";; 0.05) echo "$EP_005";; 0.1|0.10) echo "$EP_010";; 0.25) echo "$EP_025";; 1.0|1.00) echo "$EP_100";; *) echo 500;; esac; }

# Select matching runs from the manifest (columns: run_name,config,backbone,freeze_backbone,pretrained,train_fraction,condition)
# Emit: run_name|config|train_fraction
mapfile -t ROWS < <(tail -n +2 "$MANIFEST" | awk -F, \
  -v c="$COND" -v fr="$FRAC" -v bb="$BACKBONE" \
  '$7 ~ c && $6 ~ fr && $3 ~ bb {print $1"|"$2"|"$6}' )

qlog "=== matrix launcher: gpu=$CUDA_VISIBLE_DEVICES COND=/$COND/ FRAC=/$FRAC/ BACKBONE=/$BACKBONE/ -> ${#ROWS[@]} runs ==="
nvidia-smi --query-gpu=index,memory.used,memory.total --format=csv,noheader 2>&1 | tee -a "$QLOG"

for row in "${ROWS[@]}"; do
    run="${row%%|*}"; rest="${row#*|}"; cfg="${rest%%|*}"; frac="${rest##*|}"
    OUT="$MATRIX_DIR/$run"
    if [ -f "$OUT/.done" ]; then qlog "SKIP $run (.done)"; continue; fi
    ep="$(epochs_for "$frac")"
    mkdir -p "$OUT"
    qlog ">>> RUN $run  cfg=$cfg  epochs=$ep"
    fast=0
    for ((i=1;i<=MAX_TRIES;i++)); do
        [ -f "$OUT/.done" ] && break
        start=$SECONDS
        "$PY" -m scripts.train --config "$cfg" --output "$OUT" --epochs "$ep" --resume 2>&1 | tee -a "$OUT/console.log"
        rc=${PIPESTATUS[0]}; dur=$((SECONDS-start))
        qlog "    $run attempt $i rc=$rc dur=${dur}s"
        if [ "$rc" -eq 0 ]; then touch "$OUT/.done"; qlog "    $run DONE"; break; fi
        if [ "$dur" -lt "$FAST_CRASH_SECS" ]; then
            fast=$((fast+1)); qlog "    fast crash $fast/$FAST_CRASH_CAP"
            [ "$fast" -ge "$FAST_CRASH_CAP" ] && { qlog "    ABORT $run (repeated fast crash — real bug)"; break; }
        else fast=0; fi
    done
done
qlog "=== matrix launcher finished for this filter ==="
