model:
  name: stunet_huge
  weights: /home/lukas/projects/foundation_model_testing/weights/STU-Net/stunet_huge_ep4k.model
  plans_pkl: vendor/STU-Net/plan_files/Task101_TotalSegmentator/STUNetTrainer_huge__nnUNetPlansv2.1/plans.pkl
  kwargs:
    size: huge
